# -*- coding: utf-8 -*-
"""College Feedback Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usIWrUN-M92m9iQyxZnC_ps9LztC3Gkm
"""

!pip install transformers datasets torch pandas

# Uploading of file
from google.colab import files
uploaded = files.upload()

#Loading the file
import pandas as pd
df = pd.read_csv("college_feedback_sample.csv")
df.head()

from transformers import pipeline

classifier = pipeline("text2text-generation", model="google/flan-t5-base")

def classify_feedback(text):
    prompt = f"Classify this college feedback into one of these categories: Academics, Facilities, Administration. Feedback: '{text}'"
    output = classifier(prompt, max_length=30)[0]['generated_text']
    return output.strip()

df['Predicted_Category'] = df['Feedback'].apply(classify_feedback)
# Saving the updated DataFrame to a new CSV
df.to_csv("classified_feedback_output.csv", index=False)

from google.colab import files
files.download("classified_feedback_output.csv")
